### ISSUE TITLE
Unable to convert hilda output file from feng-hirst-rst-parser 

### ISSUE THREAD

**Issue by Christian-Nja** [arne-cl/discoursegraphs#158]
https://github.com/arne-cl/discoursegraphs/blob/605ada7280d320615df4f7f2f9bcb3e85c33f0f2/src/discoursegraphs/readwrite/rst/hilda.py#L39-L56

I tried to redirect the output of feng hirst rst parser: 

https://github.com/arne-cl/feng-hirst-rst-parser

into the rst-converter-service:

https://github.com/NLPbox/rst-converter-service

Specifically the file i tried to pass to rst-converter-service is:

> 
> (Contrast[S][N]
>   _!Although they did n't like it ,!_
>   _!they accepted the offer . <P>!_)

that's the output of feng-hirst-rst-parser on simple text file with sentence:

> Altough they didn't like it, they accepted the offer.

To run the rst-converter-service i used this command:
`
curl -XPOST localhost:5000/convert/hilda/rs3 -F input=@input_short.txt.tree`

i got as json error returned by the docker api:

`{"error":"<class 'discoursegraphs.readwrite.rst.hilda.HILDARSTTree'> can't handle input file 'input_short.txt.tree'. Got: invalid syntax (<string>, line 2)","traceback":"Traceback (most recent call last):\n  File \"app.py\", line 111, in post\n    tree = read_function(temp_inputfile.name)\n  File \"/usr/lib/python2.7/site-packages/discoursegraphs/readwrite/rst/hilda.py\", line 33, in __init__\n    self.hildafile_tree = self.hildastr2hildatree(hilda_str)\n  File \"/usr/lib/python2.7/site-packages/discoursegraphs/readwrite/rst/hilda.py\", line 56, in hildastr2hildatree\n    return eval(parented_tree_str)\n  File \"<string>\", line 2\n    _!Although they did n't like it ,!_\n    ^\nSyntaxError: invalid syntax\n"}`

I'm pretty sure the feng-hirst-parser works because i tested it on some files and it passed all the tests and sanity-check provided by the authors and that the rst-converter-service works at least with other input format (for example from .dis to .rs3 or to .rs3 to .dis).

do you experience the same problem?

**Comment by arne-cl** [comment]
Dear Christian,

sorry for the confusion. Both [arne-cl/feng-hirst-rst-parser](https://github.com/arne-cl/feng-hirst-rst-parser) as well as [nlpbox/feng-hirst-service](https://github.com/nlpbox/feng-hirst-service) are not using the original HILDA output format, but a slightly adapted format (based on the nltk.Tree
serialization used internally by both HILDA and the Feng/Hirst parser).

You can produce/use this format as follows:

```
$ cat /tmp/input_short.txt 
Although they didn't like it, they accepted the offer.
```

```
$ docker run -p 8000:8000 -ti nlpbox/feng-hirst-service:2019-01-04
```

```
$ curl -X POST -F "input=@/tmp/input_short.txt" http://localhost:8000/parse > /tmp/input_short.hilda
$ cat /tmp/input_short.hilda
ParseTree('Contrast[S][N]', ["Although they did n't like it ,", 'they accepted the offer .'])
```

```
$ docker run -p 5000:5000 -ti nlpbox/rst-converter-service:2019-12-05-1
$ $ curl -XPOST localhost:5000/convert/hilda/rs3 -F input=@/tmp/input_short.hilda
<?xml version='1.0' encoding='UTF-8'?>
<rst>
  <header>
    <relations>
      <rel name="Contrast" type="rst"/>
    </relations>
  </header>
  <body>
    <segment id="3" parent="5" relname="Contrast">Although they did n't like it ,</segment>
    <segment id="5" parent="1" relname="span">they accepted the offer .</segment>
    <group id="1" type="span"/>
  </body>
</rst>
```

## original HILDA format

```
(Contrast[S][N]
  _!Although they did n't like it ,!_
  _!they accepted the offer . <P>!_)
```

## adapted HILDA format

```
ParseTree('Contrast[S][N]', ["Although they did n't like it ,", 'they accepted the offer .'])
```

**Comment by Christian-Nja** [comment]
Thank you very much now the docker api works perfectly! Great job!

**Comment by Syauri** [comment]
While the rst-converter-service is able to convert many of the hilda output files generated using feng-hirst-rst-parser but it is giving me memory issue for some. This is what I see:

`{"error":"<class 'discoursegraphs.readwrite.rst.hilda.HILDARSTTree'> can't handle input file 'A02.txt'. Got: ","traceback":"Traceback (most recent call last):\n  File \"app.py\", line 111, in post\n    tree = read_function(temp_inputfile.name)\n  File \"/usr/lib/python2.7/site-packages/discoursegraphs/readwrite/rst/hilda.py\", line 33, in __init__\n    self.hildafile_tree = self.hildastr2hildatree(hilda_str)\n  File \"/usr/lib/python2.7/site-packages/discoursegraphs/readwrite/rst/hilda.py\", line 56, in hildastr2hildatree\n    return eval(parented_tree_str)\nMemoryError\n"}`
